### ISSUE TITLE
[DOC] The link of forward proxy should be updated!

### ISSUE THREAD

**Issue by Milkve** [cloudwego/hertz-examples#106]
**Describe the bug**

 The link of [forward proxy](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/forward-proxy/) is 404 now. 

**To Reproduce**

1. Go to 'client/forward_proxy/README.md'
2. Click on the link of [forward proxy](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/forward-proxy/)
3. See 404 error
4. However if search in doc the content shows in [here](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/proxy/#%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86)

**Expected behavior**

The link of forward proxy should be updated. 

**Screenshots**

The link in readme shows 404 error:

![image](https://github.com/cloudwego/hertz-examples/assets/45092129/7826d4fb-2f48-4067-b066-7b095050b30e)

and I guess the link changes to 

![image](https://github.com/cloudwego/hertz-examples/assets/45092129/84b2b0ca-62c4-4990-a4f7-a210feea95ff)

and the link is changed in doc

![image](https://github.com/cloudwego/hertz-examples/assets/45092129/97407f4e-3a48-40ee-8d63-3ba2aded0e0d)

**Hertz version:**

hz version v0.6.4

**Environment:**

Just a doc issue, I believe you don't need the output of `go env`.

**Comment by GuangmingLuo** [comment]
@Milkve Hi, you may raise a pr to fix the broken link.
