### ISSUE TITLE
opentelementry的示例问题

### ISSUE THREAD

**Issue by SIN5t** [cloudwego/hertz-examples#115]
用wsl2建立了docker-compose.yml和otel-collector-config.yaml运行之后，有一个容器：opentelemetry-collector一直运行不起来

示例：
![image](https://github.com/cloudwego/hertz-examples/assets/97775060/a64d0a6e-10f7-4e91-b10d-b81e46c783a3)

本地建立yaml文件：
![image](https://github.com/cloudwego/hertz-examples/assets/97775060/a017ca67-88d0-4edc-a083-be9efe9f51b1)

docker运行：
![image](https://github.com/cloudwego/hertz-examples/assets/97775060/edbe3e8d-d590-49aa-a226-e716ab962285)

报错日志：
![image](https://github.com/cloudwego/hertz-examples/assets/97775060/82126218-07b1-449e-847b-915fbe29ee07)
看日志的意思好像是opentelemetry-collector 支持的export中不含有jaeger，有效的是这些：(valid values: [skywalking sumologic dynatrace prometheusremotewrite sapm tanzuobservability prometheus awscloudwatchlogs carbon f5cloud googlemanagedprometheus influxdb otlp otlphttp clickhouse datadog instana loadbalancing loki opencensus logging splunk_hec tencentcloud_logservice parquet awsxray azuremonitor cassandra googlecloudpubsub zipkin awss3 file logicmonitor signalfx coralogix azuredataexplorer elasticsearch googlecloud pulsar sentry alibabacloud_logservice awskinesis dataset kafka logzio mezmo awsemf])

定位到otel-collector-config.yaml中的配置：
![image](https://github.com/cloudwego/hertz-examples/assets/97775060/e9d1aa23-3ceb-4288-a2f5-38b6002d8057)
里面指定的exporters确实指定了jaeger

问题猜测：
是不是版本问题，otel-collector的最新版本中exporters不支持jaeger了？

**Comment by GuangmingLuo** [comment]
@rogerogers @CoderPoet Please take a look.

**Comment by rogerogers** [comment]
是的，新版本 jaeger 原生支持 OTLP 协议投递，jaeger exporter已经被移除了。

**Comment by rogerogers** [comment]
```yaml
exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
```
改成 otlp 应该ok的。

**Comment by SIN5t** [comment]
十分感谢！问题解决！！！

**Comment by li-jin-gou** [comment]
重新打开，原因是使用 otel 的地方需要修改此配置
