### ISSUE TITLE
POST单元测试测试咨询

### ISSUE THREAD

**Issue by FunkyGod** [cloudwego/hertz-examples#116]
首先，非常感谢开放hertz框架

我在使用[代码](https://github.com/cloudwego/hertz-examples/blob/main/bizdemo/hertz_gorm/biz/handler/user_gorm/user_service.go)这段验证的时候，使用下面的代码进行单元测试，发现Name或者name，单测用例校验都会报错
```
2023/09/26 18:19:03.283748 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/v1/user/create           --> handlerName=hertz/demo/biz/handler/user_gorm.CreateUser (num=2 handlers)
{"code":2,"msg":"validating: expr_path=Name, cause=invalid"}--- PASS: TestPerformRequest (0.04s)
```
下面是单测代码，希望能指出POST方法需要如何正确封装请求🙇‍，避免上面的问题
```
package user_gorm

import (
	"bytes"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/test/assert"
	"github.com/cloudwego/hertz/pkg/common/ut"
	"testing"
)

func TestPerformRequest(t *testing.T) {
	h := server.Default()
	h.POST("/v1/user/create", CreateUser)
	json := `{Name:"gdx", "gender": 1, "age": 10, "introduce": "?"}`
	w := ut.PerformRequest(h.Engine, "POST", "/v1/user/create",
		&ut.Body{Body: bytes.NewBufferString(json), Len: len(json)},
		ut.Header{"Connection", "close"})
	resp := w.Result()
	assert.DeepEqual(t, 200, resp.StatusCode())
	// 打印响应体
	fmt.Printf(string(resp.Body()))
}

```

**Comment by li-jin-gou** [comment]
结构体:
https://github.com/cloudwego/hertz-examples/blob/main/bizdemo/hertz_gorm/biz/hertz_gen/user_gorm/api.go#L431
![image](https://github.com/cloudwego/hertz-examples/assets/97824201/d4cef9a3-2a88-4ac9-bde3-79d15c840a5f)

这里报错是 binding 报错
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E6%94%AF%E6%8C%81%E7%9A%84-tag-%E5%8F%8A%E5%8F%82%E6%95%B0%E7%BB%91%E5%AE%9A%E4%BC%98%E5%85%88%E7%BA%A7
![image](https://github.com/cloudwego/hertz-examples/assets/97824201/51c65f84-3db2-4f4e-9238-c250de6ff994)

header 需要传递 content-type ，否则还是不会绑定 json 的

**Comment by FunkyGod** [comment]
> 结构体: https://github.com/cloudwego/hertz-examples/blob/main/bizdemo/hertz_gorm/biz/hertz_gen/user_gorm/api.go#L431 ![image](https://user-images.githubusercontent.com/97824201/270629718-d4cef9a3-2a88-4ac9-bde3-79d15c840a5f.png)
> 
> 这里报错是 binding 报错 https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E6%94%AF%E6%8C%81%E7%9A%84-tag-%E5%8F%8A%E5%8F%82%E6%95%B0%E7%BB%91%E5%AE%9A%E4%BC%98%E5%85%88%E7%BA%A7 ![image](https://user-images.githubusercontent.com/97824201/270630022-51c65f84-3db2-4f4e-9238-c250de6ff994.png)
> 
> header 需要传递 content-type ，否则还是不会绑定 json 的

![image](https://github.com/cloudwego/hertz-examples/assets/39259580/29fcddf1-7557-43a7-9999-a5dcfd300337)
这里测试发生了panic，求帮助看看呢

**Comment by FunkyGod** [comment]
> @FunkyGod 写单测需要注意 DB 等资源需要初始化，否则会空指针

![image](https://github.com/cloudwego/hertz-examples/assets/39259580/88b7d5fd-af61-4188-913c-7aca0bd432d2)
![image](https://github.com/cloudwego/hertz-examples/assets/39259580/e8baa491-3580-4113-baa8-04603d3fe8a5)
测试连接数据库DB hertz没问题，但是有panic
```
2023/09/27 17:42:46.249250 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/v1/user/create           --> handlerName=hertz/demo/biz/handler/user_gorm.CreateUser (num=2 handlers)
{gdx Male 10 ?}2023/09/27 17:42:46.265473 option.go:36: [Error] HERTZ: [Recovery] err=runtime error: invalid memory address or nil pointer dereference
stack=D:/Iwiki/工程项目/Go/go_zero/go1.21.0/src/runtime/pani    c.go:261 (0x6f31e6)
	panicmem: panic(memoryError)
D:/Iwiki/工程项目/Go/go_zero/go1.21.0/src/runtime/signal_win    dows.go:364 (0x6f31b6)
	sigpanic: panicmem()
C:/Users/admin/go/pkg/mod/gorm.io/gorm@v1.25.4/finisher_api.go:18 (0xbc34bc)
	(*DB).Create: if db.CreateBatchSize > 0 {
D:/Iwiki/工程项目/Go/hertz_demo/biz/dal/mysql/user.go:24 (0x    c06ab2)
	CreateUser: return DB.Create(users).Error
D:/Iwiki/工程项目/Go/hertz_demo/biz/handler/user_gorm/user_se    rvice.go:75 (0xc069fa)
	CreateUser: if err = mysql.CreateUser([]*user_model.User{
```
顺便请教下怎么指向user表的呢？

**Comment by li-jin-gou** [comment]
辛苦跟进一下这个 @Skyenought

**Comment by FunkyGod** [comment]
> @FunkyGod 写单测需要注意 DB 等资源需要初始化，否则会空指针
单测还是用的之前反馈的TestPerformRequest，只是加入了content-type，
“DB资源初始化”除了在dal/mysql/init.go里面指定外，还需要在单测里额外声明？
go build然后调用创建接口，也是报相同的错误

意思是需要在main和单测里都手动dal.Init()初始化是吧？

**Comment by li-jin-gou** [comment]
> > @FunkyGod 写单测需要注意 DB 等资源需要初始化，否则会空指针
> > 单测还是用的之前反馈的TestPerformRequest，只是加入了content-type，
> > “DB资源初始化”除了在dal/mysql/init.go里面指定外，还需要在单测里额外声明？
> > go build然后调用创建接口，也是报相同的错误
> 
> 意思是需要在main和单测里都手动dal.Init()初始化是吧？

是的

**Comment by FunkyGod** [comment]
![image](https://github.com/cloudwego/hertz-examples/assets/39259580/51784674-0d8d-4be0-bf0a-428650fa8df2)
![image](https://github.com/cloudwego/hertz-examples/assets/39259580/e811ed31-8255-4ac1-a819-978c77a51030)
![image](https://github.com/cloudwego/hertz-examples/assets/39259580/06624f4d-8420-45e8-acf3-5ea700bea054)
调用API反而users是空的呢？

**Comment by Skyenought** [comment]
![](https://user-images.githubusercontent.com/39259580/273358479-e811ed31-8255-4ac1-a819-978c77a51030.png)
@FunkyGod 你的 form 参数 ~~pagesize~~ 应该改为 page_size
