### ISSUE TITLE
possible to do a simple grpc example?

### ISSUE THREAD

**Issue by ouvaa** [cloudwego/hertz-examples#130]
possible to do a simple grpc example?

**Comment by li-jin-gou** [comment]
grpc Please use kitex. https://www.cloudwego.io/docs/kitex/

**Comment by ouvaa** [comment]
@li-jin-gou the problem is i need it to be cloudflare compatible, so how can i use grpc with http/2 and tls with hertz?


https://developers.cloudflare.com/network/grpc-connections/

Enable gRPC
[​​](https://developers.cloudflare.com/network/grpc-connections/#requirements)Requirements
Your gRPC endpoint must listen on port 443. 
Your gRPC endpoint must support TLS and HTTP/2.
HTTP/2 must be advertised over ALPN.
Use application/grpc or application/grpc+<message type (for example: application/grpc+proto) for the Content-Type header of gRPC requests.
Make sure that the hostname that hosts your gRPC endpoint: - Is set to [proxied](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/) - Uses at least the [Full SSL/TLS encryption mode](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full/).
[​​](https://developers.cloudflare.com/network/grpc-connections/#procedure)

**Comment by li-jin-gou** [comment]
It is not recommended to use H2 to construct the GRPC protocol. Consider using grpc or kitex-grpc directly.

**Comment by ouvaa** [comment]
@li-jin-gou i understand but as i mentioned, need cloudflare. any ways to get grpc with http2? cloudflare security is more important currently.

**Comment by li-jin-gou** [comment]
Hertz not support grpc.
