### ISSUE TITLE
[Error] HERTZ: [Recovery] err=remote or network error: get connection error: dial tcp 127.0.0.1:8888: i/o timeout #1315

### ISSUE THREAD

**Issue by haoyuxin** [cloudwego/hertz-examples#138]
在https://github.com/cloudwego/hertz-examples/hz_kitex_demo 中，hz调用kitex老是报这样的错，window11和rockylinux都试过了，都有一样的错误，是不框架本身的问题。kitex超时设置加大了也不管用

**Comment by haoyuxin** [comment]
[Error] KITEX: processing request error, remoteService=, remoteAddr=127.0.0.1:63780, error=default codec read failed: read tcp 127.0.0.1:8888->127.0.0.1:63780: i/o timeout

**Comment by li-jin-gou** [comment]
看着不像

**Comment by li-jin-gou** [comment]
这里的描述不对，其实是 kitex_cli 调用 kitex_sever
