### ISSUE TITLE
For rendering, any features to do header.tmpl / footer. tmpl etc?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz-examples#14]
i realised ctx.HTML is much slower than ctx.String... possible to speed this up? 50k req/s vs 15k req/s

For rendering, any features to do header.tmpl / footer. tmpl etc?

for header and footer so to have consistency. just curious how to stack them together. now i'm doing a lot of repeats. how to stack them together?
```
                ctx.HTML(consts.StatusOK, "index.tmpl", utils.H{
                        "t": "Main website",
                        "h": "Head website",
                        "b": "Body website",
                })

```

**Comment by FGYFFFF** [comment]
@hiqsociety  Can you use front and back-end separation design?
