### ISSUE TITLE
请问router.go, middleware.go 的模版在哪里呢？

### ISSUE THREAD

**Issue by zengxiaolou** [cloudwego/hertz-examples#140]
我现在想自定义router.go 模版，但是在代码中没找到相关的参考，自己写group 出现了一些问题，想了解一下除了examples 里面写了的handler.go, service.go 以外的模版在哪里

**Comment by tqqq** [comment]
https://github.com/cloudwego/hertz/blob/v0.9.5/cmd/hz/generator/package_tpl.go#L182
