### ISSUE TITLE
使用了update_behavior中的 type 为skip， 但是还是会更新

### ISSUE THREAD

**Issue by zengxiaolou** [cloudwego/hertz-examples#142]
![img_v3_029t_7ff6c1b7-8ef7-41d2-b18a-1f15b73724bg](https://github.com/cloudwego/hertz-examples/assets/44358506/a22ef08d-4eca-4f79-8fba-ccc6ee3e852c)

已经设置了type 为skip
![image](https://github.com/cloudwego/hertz-examples/assets/44358506/4ab09c8c-fa13-42cb-8e5e-117e9fc6a635)
但还是有生成
其他需要append的，却没有append

**Comment by li-jin-gou** [comment]
这看着是模版没生效，等 @FGYFFFF  有时间确定下.

**Comment by li-jin-gou** [comment]
使用 disable 选项
