### ISSUE TITLE
hz 集成 protoc-gen-openapi 插件报错

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/hertz-examples#143]
Describe the Question

img_v3_02a3_64145d6d-a9ff-4b76-8777-8d9b4680a9cg
按照这个示例生成文档时报错，
plugin protoc_gen_hertz returns error: exit status 1, cause:
openapiv3/annotations.proto: File not found.
google/api/annotations.proto: File not found.

Expected behavior

怎么才能导入 openapiv3/annotations.proto 和 google/api/annotations.proto

Hertz version:

v0.8.1

Environment:

go1.22.2

**Comment by FGYFFFF** [comment]
openapi.proto: https://github.com/cloudwego/hertz-examples/blob/main/hz/plugin/proto/idl/hello/hello.proto
google api: https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

**Comment by darrenxyue** [comment]
openapi.proto: https://github.com/cloudwego/hertz-examples/blob/main/hz/plugin/proto/idl/hello/hello.proto
这个不对吧

**Comment by li-jin-gou** [comment]
我记得我当时搜索了一下怎么用这个插件

**Comment by li-jin-gou** [comment]
知道了 https://stackoverflow.com/questions/66168350/import-google-api-annotations-proto-was-not-found-or-had-errors-how-do-i-add

**Comment by xuyang404** [comment]
你们有测试过hz 集成 protoc-gen-openapi 插件吗？

**Comment by li-jin-gou** [comment]
> 你们有测试过hz 集成 protoc-gen-openapi 插件吗？

example 中测试过可以跑通插件流程
