### ISSUE TITLE
cant seemed to get reverse proxy working with nginx https backend

### ISSUE THREAD

**Issue by sprappcom** [cloudwego/hertz-examples#144]
@li-jin-gou there's a domain name for the nginx-fcgi-php, no matter what i've done, it doesnt seem to recognize the https backend with response.

```
2024/05/01 07:21:14.187199 engine.go:469: [Error] HERTZ: Error=remote error: tls: unknown certificate, remoteAddr=172.17.0.1:39776
```

can anyone help? i've tried commenting and uncommenting the below etc. it's tested inside docker. shld work wherever but not working.

```
package main

import (
        //"context"
        "crypto/tls"
        "fmt"
        //"sync"

        //"github.com/cloudwego/hertz/pkg/app"
        "github.com/cloudwego/hertz/pkg/app/client"
        "github.com/cloudwego/hertz/pkg/app/server"
        "github.com/cloudwego/hertz/pkg/protocol"
        //"github.com/cloudwego/hertz/pkg/common/utils"
        //"github.com/cloudwego/hertz/pkg/app/middlewares/client/sd"
        "github.com/cloudwego/hertz/pkg/common/config"
        "github.com/cloudwego/hertz/pkg/network/standard"
        "github.com/hertz-contrib/reverseproxy"
        //"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
                cfg := &tls.Config{
                        MinVersion:               tls.VersionTLS12,
                        //CurvePreferences:         []tls.CurveID{tls.X25519, tls.CurveP256},
                        //PreferServerCipherSuites: true,
                        /*
                        CipherSuites: []uint16{
                                tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
                                tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
                                tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        },
                        */
                }
                cert, err := tls.LoadX509KeyPair("server.crt", "server.key")
                if err != nil {
                        fmt.Println(err.Error())
                }
                cfg.Certificates = append(cfg.Certificates, cert)

                h := server.New(
                        server.WithHostPorts(":443"),
                        server.WithTLS(cfg),
                )

                proxy, err := reverseproxy.NewSingleHostReverseProxy("https://172.17.0.4:443",
                        client.WithTLSConfig(&tls.Config{
                                InsecureSkipVerify: true,
                        }),
                        client.WithDialer(standard.NewDialer()),
                )
                if err != nil {
                        panic(err)
                }
        proxy.SetDirector(func(req *protocol.Request) {
                req.SetRequestURI(string(reverseproxy.JoinURLPath(req, proxy.Target)))
                req.Header.SetHostBytes(req.URI().Host())
                req.Options().Apply([]config.RequestOption{config.WithSD(true)})
        })
                h.Any("/", proxy.ServeHTTP)

                /*
        h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
                ctx.String(consts.StatusOK, "TLS test\n")
        })
        */

                h.Spin()

}
```

**Comment by sprappcom** [comment]
@li-jin-gou 
there doesnt seem to have a setschemebytes option. how to set the scheme as https or whatever the req.URI is?

req.SetSchemeBytes undefined (type *protocol.Request has no field or method SetSchemeBytes)

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz-examples/blob/main/reverseproxy/tls/main.go

**Comment by li-jin-gou** [comment]
I found out why proxy doesn't use tls config?
![image](https://github.com/cloudwego/hertz-examples/assets/97824201/8b1ac6f1-a54b-419e-9119-f56623d8821c)

**Comment by sprappcom** [comment]
@li-jin-gou ok thx, will try in a few days, i sick today.

**Comment by sprappcom** [comment]
@li-jin-gou where is the code change? what do u really mean? i dont see any difference in what u mentioned?

i think it's not using https set scheme. right? my code has everything except set scheme

**Comment by li-jin-gou** [comment]
> where is the code change? what do u really mean? i dont see any difference in what u mentioned?
> 
> i think it's not using https set scheme. right? my code has everything except set scheme

No. What I mean is that there is no tls configuration for the reverse proxy client which is causing the error.

Have you looked at debugging debug with breakpoints?

**Comment by sprappcom** [comment]
@li-jin-gou can you just provide an answer? gimme a hint how to get it done

**Comment by li-jin-gou** [comment]
My computer is down and I can't give you a direct answer to the code, if you can give a locally runnable code I think others can help.

Also I think I made it clear enough, if you can fix it by looking at the hertz tls and the repercussions bring documentation I think that's great.

I got a similar error using google browser, it's not a framework issue, but of course if you can look at the stak overflow I think you can get an answer.


Finally if you can't solve it I'd like to see a local reproduction of the code that works, so that others can see it and help solve it! @sprappcom

**Comment by sprappcom** [comment]
@li-jin-gou this is the code i mentioned previously, pasting it again.

when will your computer be up again? please just gimme a working solution. thx in advance

```
package main

import (
        //"context"
        "crypto/tls"
        "fmt"
        //"sync"

        //"github.com/cloudwego/hertz/pkg/app"
        "github.com/cloudwego/hertz/pkg/app/client"
        "github.com/cloudwego/hertz/pkg/app/server"
        "github.com/cloudwego/hertz/pkg/protocol"
        //"github.com/cloudwego/hertz/pkg/common/utils"
        //"github.com/cloudwego/hertz/pkg/app/middlewares/client/sd"
        "github.com/cloudwego/hertz/pkg/common/config"
        "github.com/cloudwego/hertz/pkg/network/standard"
        "github.com/hertz-contrib/reverseproxy"
        //"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
                cfg := &tls.Config{
                        MinVersion:               tls.VersionTLS12,
                        //CurvePreferences:         []tls.CurveID{tls.X25519, tls.CurveP256},
                        //PreferServerCipherSuites: true,
                        /*
                        CipherSuites: []uint16{
                                tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
                                tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
                                tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        },
                        */
                }
                cert, err := tls.LoadX509KeyPair("server.crt", "server.key")
                if err != nil {
                        fmt.Println(err.Error())
                }
                cfg.Certificates = append(cfg.Certificates, cert)

                h := server.New(
                        server.WithHostPorts(":443"),
                        server.WithTLS(cfg),
                )

                proxy, err := reverseproxy.NewSingleHostReverseProxy("https://172.17.0.4:443",
                        client.WithTLSConfig(&tls.Config{
                                InsecureSkipVerify: true,
                        }),
                        client.WithDialer(standard.NewDialer()),
                )
                if err != nil {
                        panic(err)
                }
        proxy.SetDirector(func(req *protocol.Request) {
                req.SetRequestURI(string(reverseproxy.JoinURLPath(req, proxy.Target)))
                req.Header.SetHostBytes(req.URI().Host())
                req.Options().Apply([]config.RequestOption{config.WithSD(true)})
        })
                h.Any("/", proxy.ServeHTTP)

                /*
        h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
                ctx.String(consts.StatusOK, "TLS test\n")
        })
        */

                h.Spin()

}
```

**Comment by li-jin-gou** [comment]
I don't know, hopefully someone else can run your code and fix it.

**Comment by li-jin-gou** [comment]
@Skyenought  Can you help me out, I'm looking at the code right now and I see that the code doesn't provide a service address for https://172.17.0.4:443?

**Comment by li-jin-gou** [comment]
As an aside, the code you provided won't run locally because https://172.17.0.4:443 doesn't start the service @sprappcom

**Comment by sprappcom** [comment]
@li-jin-gou i'm actually using fasthttp to manually convert hertz client to fasthttp client just to communicate with the nginx tls which works. possible to make this work without the fasthttp conversion?

**Comment by sprappcom** [comment]
@li-jin-gou pls help again on this issue. thx

**Comment by li-jin-gou** [comment]
My computer is broken. You can try debugging yourself to find out the problem, or wait until my computer becomes normal. 😰



---Original---
From: ***@***.***&gt;
Date: Sun, May 5, 2024 17:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudwego/hertz-examples] cant seemed to get reverse proxyworking with nginx https backend (Issue #144)




 
@li-jin-gou pls help again on this issue. thx

**Comment by li-jin-gou** [comment]
Can you try debugging it yourself? Maybe you can solve it yourself.





---Original---
From: ***@***.***&gt;
Date: Sun, May 5, 2024 17:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudwego/hertz-examples] cant seemed to get reverse proxyworking with nginx https backend (Issue #144)




 
@li-jin-gou pls help again on this issue. thx

**Comment by li-jin-gou** [comment]
I have seen that it is normal for others to reverse proxy TLS. Can you check it yourself?




---Original---
From: ***@***.***&gt;
Date: Sun, May 5, 2024 17:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudwego/hertz-examples] cant seemed to get reverse proxyworking with nginx https backend (Issue #144)




 
@li-jin-gou pls help again on this issue. thx

**Comment by Skyenought** [comment]
Are you sure you specified the `go net` network library in server?

```go
server.New(server.WithTransport(standard.NewTransporter))
```

**Comment by sprappcom** [comment]
@li-jin-gou i wait u.
@Skyenought i try tml.

**Comment by li-jin-gou** [comment]
I have searched using google browser and this is not a hertz issue but a certificate issue?

**Comment by li-jin-gou** [comment]
Why don't you try to use a search engine solution or debug debugging?

**Comment by li-jin-gou** [comment]
![image](https://github.com/cloudwego/hertz-examples/assets/97824201/aa8154a0-4bc8-453d-bcce-509d5972e977)

https://www.google.com.hk/search?q=tls%3A+unknown+certificate%2C+golang&oq=tls%3A+unknown+certificate%2C+golang&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg60gEIMjM1MWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8

https://stackoverflow.com/questions/65838917/could-not-read-from-connectionremote-error-tls-unknown-certificate


Here are the search results, you can search for them yourself, it's not a hertz problem.

**Comment by sprappcom** [comment]
@li-jin-gou no it's not cert issue. i try first and revert. it's not cert issue. pls let me close this when i finished confirmed

**Comment by li-jin-gou** [comment]
I've solved the problem based on the browser prompts and I think you can too, it's not a hertz problem.。。。。

**Comment by sprappcom** [comment]
@li-jin-gou because i used self signed and use internal https:// server, it will work but it will not work if it's using nginx tls backend. so it has nothing to do with the browser https. only not working if the backend uses nginx tls server

**Comment by sprappcom** [comment]
@li-jin-gou, it is not showing

1. https
2. the domain name from browser. it's supposed to be example.com or something but it's not showing any domain name.

how to fix it?
```
nginx_access_log 
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
172.17.0.1	-	172.17.0.3/	GET / HTTP/1.1	302
```

**Comment by sprappcom** [comment]
@li-jin-gou @Skyenought i found out that req.URI().Host() is not working, how to get the Host and URI etc?
```
        proxy.SetDirector(func(req *protocol.Request) {
                req.SetRequestURI(string(reverseproxy.JoinURLPath(req, proxy.Target)))
                req.Header.SetHostBytes(req.URI().Host())
                req.Options().Apply([]config.RequestOption{config.WithSD(true)})
        })
        ```

**Comment by sprappcom** [comment]
@li-jin-gou @Skyenought setrequesturi is not working for me this way now. how to resolve? both code also not working.

it says 404 not found on nginx server end.

**Comment by sprappcom** [comment]
@li-jin-gou @Skyenought 

how to resolve? setrequesturi is not working for everything that's /* 

pls check your example, it's flawed.
```
        proxy.SetDirector(func(req *protocol.Request) {
                log.Printf("req = %s = %s", req.URI(), req.Host())
                req.Header.SetHostBytes(req.URI().Host())
                req.SetRequestURI(string(reverseproxy.JoinURLPath(req, proxy.Target)))
                req.Options().Apply([]config.RequestOption{config.WithSD(true)})
        })
        h.Any("/:any", proxy.ServeHTTP)
        h.Any("/", proxy.ServeHTTP)
```

**Comment by Skyenought** [comment]
@sprappcom No, you can do it
you can visit `https://localhost:8005/backend/{param}` 
```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/hertz-contrib/reverseproxy"
)

var (
	wg        sync.WaitGroup
	tlsConfig *tls.Config
)

func main() {
	wg.Add(2)
	cert, err := tls.LoadX509KeyPair("tls/server.crt", "tls/server.key")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	tlsConfig = &tls.Config{
		MinVersion:               tls.VersionTLS12,
		CurvePreferences:         []tls.CurveID{tls.X25519, tls.CurveP256},
		PreferServerCipherSuites: true,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		},
	}

	tlsConfig.Certificates = append(tlsConfig.Certificates, cert)

	go func() {
		defer wg.Done()
		h := server.New(
			server.WithHostPorts(":8004"),
			server.WithTLS(tlsConfig),
			// if you want to use tls server. pls use go net
			server.WithTransport(standard.NewTransporter),
		)
		backend := h.Group("/backend")
		backend.GET("/", func(cc context.Context, c *app.RequestContext) {
			c.JSON(200, utils.H{"msg": "pong"})
		})
		backend.GET("/hello", func(cc context.Context, c *app.RequestContext) {
			c.JSON(200, utils.H{"msg": "hello"})
		})
		backend.GET("/:param", func(c context.Context, ctx *app.RequestContext) {
			ctx.JSON(200, utils.H{"msg": ctx.Param("param")})
		})
		h.Spin()
	}()

	go func() {
		defer wg.Done()
		h := server.New(
			server.WithHostPorts(":8005"),
			server.WithTransport(standard.NewTransporter),
			server.WithTLS(tlsConfig),
		)
		target := "https://localhost:8004"
		proxy, err := reverseproxy.NewSingleHostReverseProxy(target,
			client.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),
			client.WithDialer(standard.NewDialer()),
		)
		if err != nil {
			panic(err)
		}
		h.GET("/backend/*any", proxy.ServeHTTP)
		h.Spin()
	}()
	wg.Wait()
}

```

**Comment by sprappcom** [comment]
@Skyenought u dont have setdirector. it's not working because the domain name information is not routed to the backend nginx server

**Comment by Skyenought** [comment]
@sprappcom In fact, it has a default director built in
![image](https://github.com/cloudwego/hertz-examples/assets/70408571/6e2049fa-f99d-4818-a291-4e9a9365833f)
