### ISSUE TITLE
无法实现事例中，trace_id的打印

### ISSUE THREAD

**Issue by antyiwei** [cloudwego/hertz-examples#146]
无法实现下面log输出
https://github.com/cloudwego/hertz-examples/tree/main/opentelemetry#tracing-associated-logs

我的代码
`package main

import (
	"context"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	hertzlogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
)

func init() {
	hlog.SetLogger(hertzlogrus.NewLogger())
	hlog.SetLevel(hlog.LevelDebug)

}
func main() {

	tracer, cfg := hertztracing.NewServerTracer()
	h := server.Default(tracer,
		server.WithHostPorts("0.0.0.0:8181"),
	)
	h.Use(hertztracing.ServerMiddleware(cfg))

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxDebugf(c, "%v", "111111")
		hlog.CtxDebugf(c, "%v", "222222")

		/*
				{
			  "level": "debug",
			  "msg": "message received successfully: my request",
			  "span_id": "445ef16484a171b8",
			  "time": "2022-07-04T06:27:35+08:00",
			  "trace_flags": "01",
			  "trace_id": "e9e579b32c9d6b0598f8f33d65689e06" // 未打印！！！
			}
		*/
		ctx.JSON(200, utils.H{"ping": "pong"})
	})

	h.Spin()
}

func AccessLog() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		start := time.Now()
		ctx.Next(c)
		end := time.Now()
		latency := end.Sub(start).Microseconds
		hlog.CtxTracef(c, "status=%d cost=%d method=%s full_path=%s client_ip=%s host=%s",
			ctx.Response.StatusCode(), latency,
			ctx.Request.Header.Method(), ctx.Request.URI().PathOriginal(), ctx.ClientIP(), ctx.Request.Host())
	}
}
`

我的输出：
`{"level":"debug","msg":"HERTZ: Method=GET    absolutePath=/ping                     --\u003e handlerName=main.main.func1 (num=4 handlers)","time":"2024-05-24T15:36:18+08:00"}
{"level":"info","msg":"HERTZ: Using network library=netpoll","time":"2024-05-24T15:36:18+08:00"}
{"level":"info","msg":"HERTZ: HTTP server listening on address=[::]:8181","time":"2024-05-24T15:36:18+08:00"}
{"level":"debug","msg":"111111","time":"2024-05-24T15:36:19+08:00"}
{"level":"debug","msg":"222222","time":"2024-05-24T15:36:19+08:00"}

`

**Comment by cqqqq777** [comment]
需要为你 hz 服务添加上 trace 相关中间件，类似
``` go
p := provider.NewOpenTelemetryProvider(
        provider.WithServiceName(serviceName),
        provider.WithExportEndpoint("localhost:4317"),
        provider.WithInsecure(),
    )
    defer p.Shutdown(context.Background())

tracer, cfg := hertztracing.NewServerTracer()
    h := server.Default(tracer)
    h.Use(hertztracing.ServerMiddleware(cfg))
```
在你 link 的文档中是写了的

**Comment by antyiwei** [comment]
我只想打印trac_id,不进行上报。是否存在开关进行控制尼?

{"level":"debug","msg":"message received successfully: 22222222222","span_id":"6b29b968e37741db","time":"2024-05-27T15:46:30+08:00","trace_flags":"01","trace_id":"1bafa2296c7d9321d2fbc04164039892"}
{"level":"debug","msg":"message received successfully: 33333333333","span_id":"6b29b968e37741db","time":"2024-05-27T15:46:30+08:00","trace_flags":"01","trace_id":"1bafa2296c7d9321d2fbc04164039892"}
2024/05/27 15:46:42 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4317: connect: connection refused"

**Comment by li-jin-gou** [comment]
cc @cqqqq777

**Comment by li-jin-gou** [comment]
cc @CoderPoet

**Comment by antyiwei** [comment]
package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hertzlogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	"github.com/hertz-contrib/obs-opentelemetry/provider"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
)

func main() {
	hlog.SetLogger(hertzlogrus.NewLogger())
	hlog.SetLevel(hlog.LevelDebug)

	//serviceName := "echo-client"
	p := provider.NewOpenTelemetryProvider(
		//provider.WithServiceName(serviceName),
		//provider.WithExportEndpoint("localhost:4317"),
		//provider.WithInsecure(),
		provider.WithEnableMetrics(false),
		provider.WithEnableTracing(true),
	)
	defer p.Shutdown(context.Background())

	tracer, cfg := hertztracing.NewServerTracer()

	h := server.Default(tracer)
	h.Use(hertztracing.ServerMiddleware(cfg))

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {

		hlog.CtxDebugf(c, "message received successfully: %d", 22222222222)

		hlog.CtxDebugf(c, "message received successfully: %d", 33333333333)
		ctx.JSON(consts.StatusOK, map[string]interface{}{
			"code": consts.StatusOK,
		})
	})

	h.Spin()
}

**Comment by antyiwei** [comment]
我想通过
<img width="645" alt="image" src="https://github.com/cloudwego/hertz-examples/assets/26668105/fb6b5903-896b-4716-ba18-5d24410d87a9">


provider.WithEnableMetrics(false)

无法实现 《打印trace_id,不进行上报》

**Comment by rogerogers** [comment]
https://github.com/hertz-contrib/obs-opentelemetry/issues/30 参考下这个

**Comment by antyiwei** [comment]
是我想要的结果。谢谢！


<img width="1015" alt="image" src="https://github.com/cloudwego/hertz-examples/assets/26668105/526ef722-49a9-474a-8353-438e2572ba2d">
这里的说明，真让人误导。

**Comment by rogerogers** [comment]
我们优化下
