### ISSUE TITLE
how to do gzip / brotli content-encoding?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz-examples#15]
how to do gzip / brotli content-encoding?

**Comment by FGYFFFF** [comment]
> how to do gzip / brotli content-encoding?

@hiqsociety Hi~ The gzip middleware is not currently available to the public, would you be interested in contributing a gzip middleware?

**Comment by li-jin-gou** [comment]
refer to https://github.com/gin-contrib/gzip @hiqsociety
