### ISSUE TITLE
monitoring doc issue

### ISSUE THREAD

**Issue by ivorysillegalss** [cloudwego/hertz-examples#165]
**Describe the bug**

in “https://github.com/cloudwego/hertz-examples/tree/main/monitoring”  `README.md`, 
the server code block import `github.com/cloudwego/monitor-prometheus` which may be deprecated. 

but in `main.go` in same dir, it is correctly imported as `prometheus "github.com/hertz-contrib/monitor-prometheus" `

**To Reproduce**

in `README.md` of "https://github.com/cloudwego/hertz-examples/tree/main/monitoring"

**Expected behavior**

should be `github.com/hertz-contrib/monitor-prometheus`

**Screenshots**

in `README.md`
![image](https://github.com/user-attachments/assets/8bb38fb7-1741-4c1a-aead-3226c1dc206c)

in `main.go`
![image](https://github.com/user-attachments/assets/26d40052-e0dc-4f58-ad15-169cf4b7ad36)

**Comment by rogerogers** [comment]
Thank you for your feedback.
