### ISSUE TITLE
运行example下的示例报错

### ISSUE THREAD

**Issue by lcsin** [cloudwego/hertz-examples#17]
我通过 git 下载了 example 项目，在 hello 目录下，运行 go run main.go 时，报了如下的错误，我的运行环境是 Win10。
在运行example项目之前， 还运行了文档中的快速开始。用 hz new 创建了一个快速开始的项目，并且运行成功。
![7591eb485e0346c752c22b4a34a1fa5](https://user-images.githubusercontent.com/49903755/177675839-9c06fd5c-1a73-4c9c-8df9-c5edc74a0973.png)

**Comment by li-jin-gou** [comment]
@lcsin  看了一下 `go.mod`  hertz 版本还是 `v0.0.1`，不支持 `windows`

**Comment by li-jin-gou** [comment]
可以拉一下最新代码，版本更新了～
