### ISSUE TITLE
jade templating example please? sorry coz jade is fastest. how to integrate as an example? 

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz-examples#29]
the current templating engine offered by hertz example... is it as performant / 0 byte allocs like jade?
https://github.com/cloudwego/hertz/issues/119

also, i think the current one is quite difficult to use. since jade is also diff, might as well just use jade.

**Comment by Haswf** [comment]
I don't think Hertz currently provides a template engine out of box right now. Can you attach a link to an example?
Also, You can integrate Hertz with using [adaptors](https://github.com/cloudwego/hertz/tree/develop/pkg/common/adaptor). However, this conpability comes at the cost of performance loss, their is no benchmark on how much the performance loss would be. The community is working on further explain the use of these adaptor in documentation. You may check out this https://github.com/cloudwego/hertz/issues/185 for update.
