### ISSUE TITLE
Proposal: add gRPC example

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz-examples#43]
**Is your feature request related to a problem? Please describe.**

Although we already have kitex, it cannot be ruled out that many users still use gRPC.

**Describe the solution you'd like**

add gRPC example.

**Additional context**

I'd like to try to resolve it if it is ok.

**Comment by li-jin-gou** [comment]
kitex support grpc.

**Comment by L2ncE** [comment]
> kitex support grpc.

got it.
