### ISSUE TITLE
streaming example, chunked body error

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz-examples#44]
**Describe the bug**

i found that ([streaming example](https://github.com/cloudwego/hertz-examples/tree/main/streaming)) use `chunked`, by setting `contentLength = - 1` but the body is not the chunked body, chunked body can be found in [here](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Transfer-Encoding), the example may mix the `streaming `and `chunked`

**Comment by welkeyever** [comment]
cc @FGYFFFF

**Comment by FGYFFFF** [comment]
"contentLength = - 1" is a flag for the framework to handle chunks, which are automatically encoded internally and set to "Transfer-Encoding"
