### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by userma000913** [cloudwego/hertz-examples#65]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

  POST http://localhost:5173/api/route_name 500 (Internal Server Error)
前后端联调时，一直报500，应该就是后端的跨域配置有问题， 前端配置了 myAxios.defaults.withCredentials = true; 
后端使用cors无效
	h.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowCredentials: true,
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Length", "Content-Type"},
	}))

换成gin框架就可以，是我配置的有问题嘛

**Comment by BaiZe1998** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> 
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> 
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> 
> Add any other context or screenshots about the feature request here.
> 
> POST http://localhost:5173/api/route_name 500 (Internal Server Error) 前后端联调时，一直报500，应该就是后端的跨域配置有问题， 前端配置了 myAxios.defaults.withCredentials = true; 后端使用cors无效 h.Use(cors.New(cors.Config{ AllowAllOrigins: true, AllowCredentials: true, AllowMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}, AllowHeaders: []string{"Origin", "Content-Length", "Content-Type"}, }))
> 
> 换成gin框架就可以，是我配置的有问题嘛

Can you show the error message from the hertz server?

**Comment by userma000913** [comment]
> 

hertz没报错。。。

**Comment by BaiZe1998** [comment]
> > 
> 
> hertz没报错。。。

Maybe you can show the debug information of the browser in developer mode.
And I would like to know the content of the request (HTTP Header & Body) initiated by your client, does it contain the Origin header field?

**Comment by userma000913** [comment]
> > > 
> > 
> > 
> > hertz没报错。。。
> 
> Maybe you can show the debug information of the browser in developer mode. And I would like to know the content of the request (HTTP Header & Body) initiated by your client, does it contain the Origin header field?

<img width="825" alt="image" src="https://user-images.githubusercontent.com/74233682/208674763-7fd79f7c-0838-4263-a917-ab72f1816ed5.png">

**Comment by BaiZe1998** [comment]
> > > > 
> > > 
> > > 
> > > hertz没报错。。。
> > 
> > 
> > Maybe you can show the debug information of the browser in developer mode. And I would like to know the content of the request (HTTP Header & Body) initiated by your client, does it contain the Origin header field?
> 
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/74233682/208674763-7fd79f7c-0838-4263-a917-ab72f1816ed5.png">

Is this the preflight request with the corresponding response, and can you show the 500 error message you mentioned?

**Comment by userma000913** [comment]
> > > > > 
> > > > 
> > > > 
> > > > hertz没报错。。。
> > > 
> > > 
> > > Maybe you can show the debug information of the browser in developer mode. And I would like to know the content of the request (HTTP Header & Body) initiated by your client, does it contain the Origin header field?
> > 
> > 
> > <img alt="image" width="825" src="https://user-images.githubusercontent.com/74233682/208674763-7fd79f7c-0838-4263-a917-ab72f1816ed5.png">
> 
> Is this the preflight request with the corresponding response, and can you show the 500 error message you mentioned? By the way, i found some fields missing in the response header.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/74233682/208687621-de0f0305-cd24-4d82-a9e0-23433a043013.png">
 我好像找到问题所在了

**Comment by BaiZe1998** [comment]
> myAxios.defaults.withCredentials = true;

This doesn't seem to be a server-side issue, is it related to the `myAxios.defaults.withCredentials = true` you mentioned? If you find an idea to solve the problem, please share it.
