### ISSUE TITLE
登录的时候使用jwt的插件，如果参数名字不对返回307，使用postman请求时返回404，其次设置content-type=text/html，返回结果为text/plain格式

### ISSUE THREAD

**Issue by Zhan-boyi** [cloudwego/hertz-examples#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by Zhan-boyi** [comment]
func InitJwt() {
	var err error
	JwtMiddleware, err = jwt.New(&jwt.HertzJWTMiddleware{
		Realm:         "test zone",
		Key:           []byte("sdskdsdksdsdskdsk key"),
		Timeout:       time.Hour,
		MaxRefresh:    time.Hour,
		TokenLookup:   "header: Authorization, query: token, cookie: token",
		TokenHeadName: "Bearer",
		LoginResponse: func(ctx context.Context, c *app.RequestContext, code int, token string, expire time.Time) {
			c.JSON(http.StatusOK, utils.H{
				"RetCode": fmt.Sprintf("%d", code),
				"Token":   token,
				"Expire":  expire.Format(http.TimeFormat),
				"RetMsg":  statuscode.CodeSuccess,
			})
		},
		Authenticator: func(ctx context.Context, c *app.RequestContext) (interface{}, error) {
			var loginStruct struct {
				UserName string `form:"Username" json:"Username" query:"Username" vd:"(len($) > 0 && len($) < 30); msg:'Illegal format'"`
				Password string `form:"Password" json:"Password" query:"Password" vd:"(len($) > 0 && len($) < 30); msg:'Illegal format'"`
			}
			if err := c.BindAndValidate(&loginStruct); err != nil {
				return nil, err
			}
			users, err := model.SysUserDaoInstance().CheckUser(loginStruct.UserName, utils2.MD5(loginStruct.Password))
			if err != nil {
				return nil, err
			}
			if len(users) == 0 {
				return nil, errors.New("user already exists or wrong password")
			}

			return users[0], nil
		},
		IdentityKey: IdentityKey,
		IdentityHandler: func(ctx context.Context, c *app.RequestContext) interface{} {
			claims := jwt.ExtractClaims(ctx, c)
			return &model.SysUser{
				UserName: claims[IdentityKey].(string),
			}
		},
		PayloadFunc: func(data interface{}) jwt.MapClaims {
			if v, ok := data.(*model.SysUser); ok {
				return jwt.MapClaims{
					IdentityKey: v.UserName,
				}
			}
			return jwt.MapClaims{}
		},
		HTTPStatusMessageFunc: func(e error, ctx context.Context, c *app.RequestContext) string {
			hlog.CtxErrorf(ctx, "jwt biz err = %+v", e.Error())

			return e.Error()
		},
		Unauthorized: func(ctx context.Context, c *app.RequestContext, code int, message string) {
			hlog.CtxErrorf(ctx, "Unauthorized = %+v", code)
			c.Redirect(307, []byte("/login"))
			c.SetContentType("text/html")
			//c.String(http.StatusTemporaryRedirect, "message:%+v", message)
		},
	})
	if err != nil {
		panic(err)
	}
}

**Comment by Zhan-boyi** [comment]
![1675096305363](https://user-images.githubusercontent.com/52889559/215536621-fe37eb6a-372b-46d9-a7bd-5df6a2fe93d0.png)
Username 后面多了一个1，名字不对

**Comment by Zhan-boyi** [comment]
![1675096425480](https://user-images.githubusercontent.com/52889559/215537746-9cbaeb6b-5b90-407a-8359-aa1c6d7a8d04.png)
![1675096379205](https://user-images.githubusercontent.com/52889559/215537759-51d00f99-1097-4ed2-8717-6b45cd6b1db5.png)

**Comment by li-jin-gou** [comment]
应该是重定向到错误的路由导致了 404
