### ISSUE TITLE
使用hertz 进行302重定向

### ISSUE THREAD

**Issue by Zhan-boyi** [cloudwego/hertz-examples#78]
```
nauthorized: func(ctx context.Context, c *app.RequestContext, code int, message string) {
			hlog.CtxErrorf(ctx, "Unauthorized = %+v", code)
			c.Redirect(http.StatusFound, []byte("/login"))
			c.SetContentType("text/html; charset=utf-8")
			//c.Header("Refresh", "0;url=https://www.xpybz.top/login")
			//c.String(http.StatusTemporaryRedirect, "message:%+v", message)
		},
```
登录失败返回302给浏览器，浏览器收到请求后地址栏没有变，页面也没有跳到登录页面
是我的设置有问题吗

**Comment by li-jin-gou** [comment]
抓包看下

**Comment by Zhan-boyi** [comment]
![image](https://user-images.githubusercontent.com/52889559/217027666-f95d1a09-bf1d-471d-896e-de60746067c2.png)
我先安装一下https证书

**Comment by Zhan-boyi** [comment]
![1675703049123](https://user-images.githubusercontent.com/52889559/217036637-1eb4720e-4460-4898-8304-f323ce3a23a3.png)
![1675702897716](https://user-images.githubusercontent.com/52889559/217036657-05788a78-51a2-4bc7-ae59-76e5cddc1d2a.png)

**Comment by li-jin-gou** [comment]
> ![image](https://user-images.githubusercontent.com/52889559/217027666-f95d1a09-bf1d-471d-896e-de60746067c2.png)
> 我先安装一下https证书
> 

看截图浏览器设置了 location 是 /login ，看起来是正常的，检查一下客户端逻辑吧，服务端响应是ok的

**Comment by Zhan-boyi** [comment]
这个不是和浏览器直接交互的吗，为啥涉及客户端

**Comment by StellarisW** [comment]
> 这个不是和浏览器直接交互的吗，为啥涉及客户端

这里的客户端就是指浏览器

**Comment by Zhan-boyi** [comment]
用了三台电脑试了都不行

**Comment by li-jin-gou** [comment]
> 用了三台电脑试了都不行

提供一下可以复现的基本代码，我们看下吧，光说现象看不出来问题，浏览器抓包显示的也是正常的
