### ISSUE TITLE
Add an example about a simple tiktok server project

### ISSUE THREAD

**Issue by leeeezp** [cloudwego/hertz-examples#85]
**Is your feature request related to a problem? Please describe.**

参加字节青训营，利用hertz为框架，实现了一个简易版抖音服务端，想要贡献到hertz-examples中，请问可以吗？如果可以的话，该如何修改项目代码呢？

**Additional context**

[offer_tiktok 项目代码](https://github.com/Kpole/tiktok)
[offer_tiktok 项目文档](https://nc67ofhaiu.feishu.cn/docx/SofYdtSUuoUEZPxWV3zcJEtmnCh)

**Comment by li-jin-gou** [comment]
提交PR ，CI通过&&优化一下代码，readme 英文，完善好即可。
