### ISSUE TITLE
When using zap's log extension, how to add requireId to the log, there is no context information in the zap hook

### ISSUE THREAD

**Issue by hiPsyDuck** [cloudwego/hertz-examples#92]
When using zap's log extension, how to add requireId to the log, there is no context information in the zap hook

**Comment by cqqqq777** [comment]
maybe you can use `hertzzap.WithZapOptions` to config the zap logger, such as: 
![image](https://user-images.githubusercontent.com/115757192/233781500-34fdcb0b-61dc-4d67-b1ae-763fd33ef31f.png)

**Comment by cqqqq777** [comment]
maybe you can use `WithZapOptions` to config the zap logger, such as:
![image](https://user-images.githubusercontent.com/115757192/233781542-c0b4d90f-cfc8-4df7-8cea-8d1a36be19c6.png)

**Comment by li-jin-gou** [comment]
refer to https://github.com/hertz-contrib/logger/pull/25

**Comment by li-jin-gou** [comment]
The hook function of zap is relatively weak
